// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FetchLocationsController from "./fetch_locations_controller"
application.register("fetch-locations", FetchLocationsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
